### ISSUE TITLE
Zoom & Undo

### ISSUE THREAD

**Issue by ghost** [Alpaca07/Quadrilateral_Annotation_Tool#1]
@Alpaca07 can you add the option to:
- Zoom
- Undo "by clicking Backspace to remove the latest dot mistake"

**Comment by yxgong0** [comment]
Thanks for your advice, I will consider that in the next version.

**Comment by ghost** [comment]
@Alpaca07 when will the next version be released?

**Comment by yxgong0** [comment]
I think I will finish that before the ending of this semester, which is Jan. 20, 2020
